package(default_visibility = ["//visibility:public"])

java_library(
    name = "environment",
    srcs = [
        "JcfEnvironment.java",
    ],
    deps = [
        "//:jcf_model_java_proto",
        "//:jcf_settings_profile_java_proto",
        "//src/main/java/net/brentwalther/jcf/prompt:api",
        "@maven//:com_google_guava_guava",
    ],
)
