java_test(
    name = "split_matcher_screen_test",
    srcs = [
        "SplitMatcherScreenTest.java",
    ],
    test_class = "net.brentwalther.jcf.screen.SplitMatcherScreenTest",
    deps = [
        "//:jcf_model_java_proto",
        "//src/main/java/net/brentwalther/jcf/matcher",
        "//src/main/java/net/brentwalther/jcf/model",
        "//src/main/java/net/brentwalther/jcf/prompt",
        "//src/main/java/net/brentwalther/jcf/prompt:api",
        "//src/main/java/net/brentwalther/jcf/screen",
        "//src/test/java/net/brentwalther/jcf/testing:argument_matchers",
        "//src/test/java/net/brentwalther/jcf/testing:correspondences",
        "@maven//:com_google_flogger_flogger_system_backend",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
        "@maven//:org_mockito_mockito_all",
    ],
)
