package(default_visibility = ["//visibility:public"])

java_library(
    name = "swing",
    srcs = [
        "SwingUi.java",
    ],
    deps = [
        "//src/main/java/net/brentwalther/jcf/prompt:api",
    ],
)
