java_library(
    name = "correspondences",
    testonly = 1,
    srcs = [
        "Correspondences.java",
    ],
    visibility = ["//src/test/java/net/brentwalther/jcf:__subpackages__"],
    deps = [
        "//:jcf_model_java_proto",
        "@maven//:com_google_truth_truth",
    ],
)
