package(default_visibility = ["//visibility:public"])

java_library(
    name = "formatter",
    srcs = [
        "Formatter.java",
    ],
    deps = [
        "@maven//:com_google_guava_guava",
    ],
)
