java_library(
    name = "flogger",
    srcs = [
        "JcfBackendFactory.java",
    ],
    deps = [
        #        "//:autovalue",
        #        "//:jcf_model_java_proto",
        #        "//:jcf_settings_profile_java_proto",
        #        "//src/main/java/net/brentwalther/jcf/export",
        #        "//src/main/java/net/brentwalther/jcf/matcher",
        #        "//src/main/java/net/brentwalther/jcf/model",
        #        "//src/main/java/net/brentwalther/jcf/model/importer",
        #        "//src/main/java/net/brentwalther/jcf/prompt",
        #        "//src/main/java/net/brentwalther/jcf/prompt:api",
        #        "//src/main/java/net/brentwalther/jcf/string:formatter",
        #        "@maven//:com_google_flogger_flogger",
        "@maven//:com_google_flogger_flogger_system_backend",
        #        "@maven//:com_google_guava_guava",
    ],
)
