package(default_visibility = ["//visibility:public"])

java_library(
    name = "matcher",
    srcs = [
        "SplitMatcher.java",
    ],
    deps = [
        "//:autovalue",
        "//:jcf_model_java_proto",
        "//src/main/java/net/brentwalther/jcf/model",
        "@maven//:com_google_guava_guava",
    ],
)
