java_test(
    name = "split_matcher_test",
    srcs = [
        "SplitMatcherTest.java",
    ],
    test_class = "net.brentwalther.jcf.matcher.SplitMatcherTest",
    deps = [
        "//:jcf_model_java_proto",
        "//src/main/java/net/brentwalther/jcf/matcher",
        "//src/test/java/net/brentwalther/jcf/testing:correspondences",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_truth_truth",
        "@maven//:junit_junit",
    ],
)
